GET http://localhost:8080/ca1/api/cities

###
POST http://localhost:8080/devops_starter_war_exploded/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "First Property", "str2": "Second Property"}


###
POST http://localhost:8080/ca1/api/persons
Content-Type: application/json

{
  "email": "owais@mail.com",
  "firstName": "Owais",
  "lastName": "Dashti",
  "phone": {
    "number": "50505050",
    "description": "Telmore",
    "isPrivate": false
  },
  "address": {
    "street": "Sushi Blv",
    "additionalInfo": "2th",
    "isPrivate": false,
    "cityinfo": {
      "zipCode": 3000
    }
  }
}

###
POST http://localhost:8080/ca1/api/persons/3/hobby/8
Content-Type: application/json

###
PUT http://localhost:8080/ca1/api/persons/1
Content-Type: application/json

{"email": "andreas@gmail.com",
"firstName": "Andreas",
"lastName":  "Fritzbøger"}

###
DELETE http://localhost:8080/ca1/api/persons/1
